{% set name = "llama-index-indices-managed-llama-cloud" %}
{% set version = "0.9.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_indices_managed_llama_cloud-{{ version }}.tar.gz
  sha256: 19af55da8f1218d80390fcbe5cdfef6100acc755b0177a4077a924c31a2fb345

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - deprecated ==1.2.18
    - llama-cloud ==0.1.35
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.13.0,<0.14
    - llamaindex-py-client >=0.1.19,<0.2.0

test:
  imports:
    - llama_index.indices.managed.llama_cloud
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: llama-index indices llama-cloud integration
  home: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/indices/llama-index-indices-managed-llama-cloud
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
