{% set name = "llama-index-indices-managed-llama-cloud" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index_indices_managed_llama_cloud-{{ version }}.tar.gz
  sha256: fbebff7876a219b6ab96892ae7c432a9299195fab8f67d4a4a0ebf6da210b242

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - llama-cloud >=0.0.11
    - python >=3.8.1,<4.0
    - llama-index-core >=0.11.13,<0.11.14
    - llamaindex-py-client >=0.1.19,<0.2.0

test:
  imports:
    - llama_index.indices.managed.llama_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  summary: llama-index indices llama-cloud integration
  home: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/indices/llama-index-indices-managed-llama-cloud
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
