{% set name = "llama-index-indices-managed-llama-cloud" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index_indices_managed_llama_cloud-{{ version }}.tar.gz
  sha256: 8ee6b11e47f2c5e7302a749b6e2baf893ab602967d86b13c84455b8ee1fb1404

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - llama-cloud >=0.0.6
    - python >=3.8.1,<4.0
    - llama-index-core >=0.10.48,<0.10.49
    - llamaindex-py-client >=0.1.19,<0.2.0

test:
  imports:
    - llama_index.indices.managed.llama_cloud
  commands:
    - pip check
  requires:
    - pip

about:
  summary: llama-index indices llama-cloud integration
  home: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/indices/llama-index-indices-managed-llama-cloud
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - jan-janssen
